const EventEmitter = require('events');

class EventBus extends EventEmitter {}

const eventBus = new EventBus();

eventBus.EVENTS = {
    POST_CREATED: 'POST_CREATED',
    COMMENT_CREATED: 'COMMENT_CREATED',
    POST_UPVOTED: 'POST_UPVOTED',
    POST_DOWNVOTED: 'POST_DOWNVOTED',
    POST_VIEWED: 'POST_VIEWED',
    REPUTATION_CHANGE: 'REPUTATION_CHANGE',
    TREND_STATUS_UPDATE: 'TREND_STATUS_UPDATE',
    BADGE_EARNED: 'BADGE_EARNED',
    USER_VERIFIED: 'USER_VERIFIED',
    BUSINESS_VERIFIED: 'BUSINESS_VERIFIED',
    AI_FLAGGED_SPAM: 'AI_FLAGGED_SPAM',
    AI_FLAGGED_HYPE: 'AI_FLAGGED_HYPE',
    POST_TRENDING: 'POST_TRENDING'
};

module.exports = eventBus;